AWSTemplateFormatVersion: '2010-09-09'
Description: 'This function is invoked by Sumo Logic(via Scheduled Search) through
  API Gateway. The event payload received is then forwarded to AWS Security Hub.

  '
Outputs:
  SecurityHubConnectorApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: https://${SecurityHubConnectorApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/findings
  SecurityHubConnectorFunction:
    Description: SecurityHubConnector Function ARN
    Value:
      Fn::GetAtt:
      - SecurityHubConnectorFunction
      - Arn
Resources:
  SecurityHubConnectorApiGateway:
    Properties:
      DefinitionBody:
        info:
          description: API endpoint for invoking SecurityHubConnectorFunction
          title:
            Ref: AWS::StackName
          version: 1.0.0
        paths:
          /findings:
            post:
              consumes:
              - application/json
              produces:
              - application/json
              responses: {}
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                requestParameters:
                  integration.request.header.X-Amz-Invocation-Type: '''RequestResponse'''
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecurityHubConnectorFunction.Arn}/invocations
        securityDefinitions:
          sigv4:
            in: header
            name: Authorization
            type: apiKey
            x-amazon-apigateway-authtype: awsSigv4
        swagger: '2.0'
      EndpointConfiguration: EDGE
      StageName: prod
    Type: AWS::Serverless::Api
  SecurityHubConnectorFunction:
    Properties:
      CodeUri: s3://cf-templates-5d0x5unchag-us-east-2/976f49f2f26e8410f8798028a5e57c14
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /findings
            RestApiId:
              Ref: SecurityHubConnectorApiGateway
          Type: Api
      Handler: src.securityhub_connector.lambda_handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - securityhub:BatchImportFindings
          Effect: Allow
          Resource: '*'
          Sid: AWSSecurityHubImportFindingsPolicy
      Runtime: python3.6
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
