sudo: required
dist: trusty
language: node_js
python:
- "2.7"

jobs:
  include:
    - stage: Node 8
      node_js: '8.10'
      env: FUNCTION_DIR=dlq_processor TEST_FILE=test_cwl_lambda.py

    - stage: Node 8
      node_js: '8.10'
      env: FUNCTION_DIR=loggroup-lambda-connector TEST_FILE=test_loggroup_lambda_connector.py

before_install:
- sudo apt-get install python-pip
- cd $FUNCTION_DIR
- sudo pip install -r requirements.txt
script:
- npm run build
- python $TEST_FILE

env:
  global:
  - secure: sD0RwgZ/hpx+WhuxOU1wNmm9Q+6DC0EOaJY241SrKAgsNUTAVtl6PgDWQ/7oWRpeDH4F0Tl85gFik0YQRvo909IDPZ+VLJ0Low4SlhMsxYQexCww1VvD9NoVR9cKSXNmdPKz0ioAMV9SVLijPKLxfzO4olujcFLXqr45xnwAEa+4nYIC1Q3Rw+NDI+ovN5izVrT2jERpjP4kQJM5aVJIieFD0AaHR2bsLbTaksnx1NC3evxY3UQr1TYUstoS7WBC6SpLRpN2454ecJACqvmxWMMUhK+KhpmWzi8Dsg9R2ENoGb7whBmnK2HIGEqNr5zvcBc/z3UZnDtakzsLvob/RfWwZ5e0Eg34Ru11jiDdStXv1TaO6fZZ6MkjWsdq28OnL2qhc9cgJfq8pVkqeDP3u94mgLdkKN2HgitcPuhgudT4mHSi6c3oy5NAqb65TUrIWUErww4D8iaH6rNp2FWC/ou2fFLN6x+iK+zPtNvKpTqcU6xhBjCu4Lcpq/HBXfLb/bXB3sd9JhPtflR5Ut3B7lNoHpE0/9yEtSj9Hp1ksbI9XizEjskeyqzLbQXECxpwT6T6l+X+eeZLDnZSZ7wsa1EgHrAWq1OhDcWwtzsd8h35r6NeKAaVfgIUecKbwIq+VAyRqbeSbFhJwFVRE7uxKOqXFzYspYTA/13Xht4cnf0=
