AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - ALBDeploymentType

      - Label:
          default: "AWS ALB App Configuration"
        Parameters:
          - AlbMetricsSourceCategoryName
          - AlbLogsSourceCategoryName
          - AlbCollectorName
          - AlbMetricsSourceName

      - Label:
          default: "Local Parameters"
        Parameters:
          - LambdaARN
          - RoleARN
          - AWSRegion

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      ALBDeploymentType:
        default: "Do you need to install Resources for AWS ALB App?"

      AlbMetricsSourceCategoryName:
        default: "ALB App Metric Data Source Category Name."
      AlbLogsSourceCategoryName:
        default: "ALB App Logs Data Source Category Name."
      AlbCollectorName:
        default: "ALB App Collector Name."
      AlbMetricsSourceName:
        default: "ALB App CloudWatch Metrics Source Name."
      LambdaARN:
        default: "ARN for lambda."
      RoleARN:
        default: "ARN for Sumo Logic Role."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  ALBDeploymentType:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."

  AlbMetricsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/alb/metrics
  AlbLogsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/alb/logs
  AlbCollectorName:
    Type: String
    Description: ALB App Collector Name.
    Default: AWS-Observability-ALB-Collector
  AlbMetricsSourceName:
    Type: String
    Description: ALB App CloudWatch Metrics Source Name.
    Default: AWS-Observability-ALB-CloudWatch-Source

  LambdaARN:
    Type: String
    Description: ARN for lambda.
  RoleARN:
    Type: String
    Description: ARN for Sumo Logic Role.
  AWSRegion:
    Type: String
    Description: AWS Region for the resources that need to be tagged.

Conditions:
  setupsumoresources: !Or
    - !Equals [ !Ref ALBDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref ALBDeploymentType, "App-SumoResources-AWSTags-S3Bucket" ]

Resources:

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: setupsumoresources
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref AlbCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchSource:
    DependsOn:
      - SumoHostedCollector
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !Ref AWSRegion
      namespace: AWS/ApplicationELB
      SourceName: !Ref AlbMetricsSourceName
      SourceCategory: !Ref AlbMetricsSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !Ref RoleARN

  sumoAlbApp:
    Type: Custom::App
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Alb App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricsrc: !Sub "_sourceCategory=${AlbMetricsSourceCategoryName}"
        logsrc: !Sub "_sourceCategory=${AlbLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment