AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - SumoOrganizationId
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - CollectorName

      - Label:
          default: "App Details - S3 Source Log Source Configuration"
        Parameters:
          - CreateS3Bucket
          - S3LogsBucketName
          - CreateS3LogSource
          - S3BucketPathExpression
          - S3LogsSourceName
          - S3LogsSourceCategoryName

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - CreateCloudWatchMetricsSource
          - AWSRegion
          - CloudWatchMetricsSourceName
          - CloudWatchMetricsSourceCategoryName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      SumoOrganizationId:
        default: "Sumo Logic Organization Id"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      CollectorName:
        default: "Collector Name"

      CreateS3Bucket:
        default: "Create AWS S3 Bucket"
      S3LogsBucketName:
        default: "AWS S3 Bucket Name"
      CreateS3LogSource:
        default: "Create Sumo Logic S3 Logs Source"
      S3BucketPathExpression:
        default: "Path Expression for the logs"
      S3LogsSourceName:
        default: "Sumo Logic S3 Logs Source Name"
      S3LogsSourceCategoryName:
        default: "Sumo Logic S3 Logs Source Category Name"

      CreateCloudWatchMetricsSource:
        default: "Create Sumo Logic CloudWatch Metrics Source"
      AWSRegion:
        default: "AWS Region"
      CloudWatchMetricsSourceName:
        default: "Sumo Logic CloudWatch Metrics Source Name"
      CloudWatchMetricsSourceCategoryName:
        default: "Sumo Logic CloudWatch Metrics Source Category Name"

      ParentStackName:
        default: "If Any, Name of parent Stack"
      QSS3BucketName:
        default: "S3 bucket name for code and templates"
      QSS3KeyPrefix:
        default: "S3 key prefix for code and templates"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
    AllowedPattern: ".+"
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
    AllowedPattern: ".+"
  SumoOrganizationId:
    Type: String
    Description: The Account Overview page displays information about your Sumo Logic organization.
    AllowedPattern: ".+"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String

  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-Alb-Collector

  CreateS3Bucket:
    Type: String
    Description: "Yes - Create a new S3 bucket in AWS S3.\n
                  No - Use an existing S3 bucket from AWS S3 which has ALB Logs."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  S3LogsBucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.\n
                  New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
    AllowedPattern: ".+"
  CreateS3LogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic S3 Log Source with provided bucket Name."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  S3BucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  S3LogsSourceName:
    Type: String
    Description: Change the S3 Source name to be created else default name will be used.
    Default: AWS-Alb-S3-Log-Source
  S3LogsSourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if S3 Source is not created.\n
                  New - Default will be used if S3 Source is Created"
    Default: AWS/Alb/S3/Logs

  CreateCloudWatchMetricsSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Cloud Watch Metrics Source."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  AWSRegion:
    Type: String
    Default: 'Current Region'
    Description: AWS Region for the resources that need to be tagged.
    AllowedValues:
      - 'Current Region'
      - 'All Regions'
  CloudWatchMetricsSourceName:
    Type: String
    Description: Change the CloudWatch Metrics Source name to be created else default name will be used.
    Default: AWS-Alb-CloudWatch-Metrics-Source
  CloudWatchMetricsSourceCategoryName:
    Type: String
    Description: "Existing - Change to an existing Source Category from Sumo Logic if CloudWatch Metrics Source is not created.\n
                  New - Default will be used if CloudWatch Metrics Source is Created"
    Default: AWS/Alb/CloudWatch/Metrics

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "sumologicawsobservabilityhelper"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "sumologic-aws-observability/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

Mappings:
  Region2ELBAccountId:
    us-east-1:
      AccountId: '127311923021'
    us-west-1:
      AccountId: 027434742980
    us-west-2:
      AccountId: '797873946194'
    eu-west-1:
      AccountId: '156460612806'
    ap-northeast-1:
      AccountId: '582318560864'
    ap-northeast-2:
      AccountId: '600734575887'
    ap-southeast-1:
      AccountId: '114774131450'
    ap-southeast-2:
      AccountId: '783225319266'
    ap-south-1:
      AccountId: '718504428378'
    us-east-2:
      AccountId: 033677994240
    sa-east-1:
      AccountId: '507241528517'
    cn-north-1:
      AccountId: '638102146993'
    eu-central-1:
      AccountId: 054676820928

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]
  region_value: !Equals [!Ref AWSRegion, 'All Regions']

  create_target_s3_bucket: !Equals [!Ref CreateS3Bucket, 'Yes']
  install_s3_logs_source: !Equals [!Ref CreateS3LogSource, 'Yes']
  install_cloud_watch_metric_source: !Equals [!Ref CreateCloudWatchMetricsSource, 'Yes']
  install_collector: !Or
    - !Condition install_s3_logs_source
    - !Condition install_cloud_watch_metric_source

Resources:
  SumoLogicHelperRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  SumoLogicHelperFunction:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLogicHelperRole
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !If [do_not_use_parent_stack, !Sub "${QSS3BucketName}-${AWS::Region}", !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

  SumoRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::926226587429:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                  - tag:GetResources
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                Resource:
                  "*"

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_collector
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !If [do_not_use_parent_stack, !Ref RemoveSumoResourcesOnDeleteStack, false]
      CollectorName: !Ref CollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchMetricsSource:
    Condition: install_cloud_watch_metric_source
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !If [region_value, "all", !Ref "AWS::Region"]
      Namespaces:
        - 'AWS/ApplicationELB'
      SourceName: !Ref CloudWatchMetricsSourceName
      SourceCategory: !Ref CloudWatchMetricsSourceCategoryName
      CollectorId: !If
        - install_cloud_watch_metric_source
        - !GetAtt
          - SumoHostedCollector
          - COLLECTOR_ID
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-CollectorID'
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'

  sumoApp:
    Type: Custom::App
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Alb App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricsrc: !Sub "_sourceCategory=${CloudWatchMetricsSourceCategoryName}"
        logsrc: !Sub "_sourceCategory=${S3LogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  TargetS3Bucket:
    Condition: create_target_s3_bucket
    Type: AWS::S3::Bucket
    DependsOn:
      - SumoSNSpolicy
    Properties:
      BucketName: !Ref S3LogsBucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref SumoSNSTopic

  SumoS3BucketPolicy:
    Condition: install_s3_logs_source
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3LogsBucketName
      PolicyDocument:
        Statement:
          - Sid: AWSAlbLogsPutObjects
            Effect: Allow
            Principal:
              AWS: !Join
              - ""
              - - "arn:aws:iam::"
                - !FindInMap [Region2ELBAccountId, !Ref 'AWS::Region', AccountId]
                - ":root"
            Action: s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${S3LogsBucketName}/*"
    DependsOn:
      - TargetS3Bucket

  SumoSNSTopic:
    Condition: install_s3_logs_source
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  SumoSNSSubscription:
    Condition: install_s3_logs_source
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn:
        Ref: SumoSNSTopic
      Endpoint: !GetAtt SumoS3Source.SUMO_ENDPOINT
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential

  SumoSNSpolicy:
    Condition: install_s3_logs_source
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
          - Action:
              - sns:Publish
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${S3LogsBucketName}"
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              - !Ref SumoSNSTopic
      Topics:
        - Ref: SumoSNSTopic

  SumoS3Source:
    Condition: install_s3_logs_source
    Type: Custom::AWSSource
    Properties:
      SourceType: AwsS3Bucket
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      SourceName: !Ref S3LogsSourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref S3LogsSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      TargetBucketName: !Ref S3LogsBucketName
      PathExpression: !Ref S3BucketPathExpression
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'