AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - APIGatewayDeploymentType

      - Label:
          default: "AWS Api Gateway App Configuration"
        Parameters:
          - ApiGatewayMetricsSourceCategoryName
          - ApiGatewayLogSourceCategoryName
          - ApiGatewayCollectorName

      - Label:
          default: "Local Parameters"
        Parameters:
          - LambdaARN
          - RoleARN

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      APIGatewayDeploymentType:
        default: "Do you need to install Resources for AWS API Gateway App?"

      ApiGatewayMetricsSourceCategoryName:
        default: "Api Gateway App Metric Data Source Category Name."
      ApiGatewayLogSourceCategoryName:
        default: "Api Gateway App Log Data Source Category Name."
      ApiGatewayCollectorName:
        default: "API Gateway App Collector Name."
      LambdaARN:
        default: "ARN for lambda."
      RoleARN:
        default: "ARN for Sumo Logic Role."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  APIGatewayDeploymentType:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."

  ApiGatewayMetricsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/apigateway/metrics
  ApiGatewayLogSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/apigateway/logs
  ApiGatewayCollectorName:
    Type: String
    Description: API Gateway App Collector Name.
    Default: AWS-Observability-API-Gateway-Collector

  LambdaARN:
    Type: String
    Description: ARN for lambda.
  RoleARN:
    Type: String
    Description: ARN for Sumo Logic Role.

Conditions:
  setupsumoresources: !Or
    - !Equals [ !Ref APIGatewayDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref APIGatewayDeploymentType, "App-SumoResources-AWSTags-S3Bucket" ]

Resources:

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: setupsumoresources
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref ApiGatewayCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  sumoApiGatewayApp:
    Type: Custom::App
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Api Gateway App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricssrc: !Sub "_sourceCategory=${ApiGatewayMetricsSourceCategoryName}"
        logsrc: !Sub "_sourceCategory=${ApiGatewayLogSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment