AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - DynamoDBDeploymentType

      - Label:
          default: "AWS DynamoDB App Configuration"
        Parameters:
          - DynamoDbMetricsSourceCategoryName
          - DynamoDbLogsSourceCategoryName
          - DynamoDbCollectorName
          - DynamoDbMetricsSourceName

      - Label:
          default: "Local Parameters"
        Parameters:
          - LambdaARN
          - RoleARN
          - AWSRegion

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      DynamoDBDeploymentType:
        default: "Do you need to install Resources for AWS Dynamo DB App?"

      DynamoDbMetricsSourceCategoryName:
        default: "Dynamo DB App Metric Data Source Category Name."
      DynamoDbLogsSourceCategoryName:
        default: "Dynamo DB App Logs Data Source Category Name."
      DynamoDbCollectorName:
        default: "Dynamo DB App Collector Name."
      DynamoDbMetricsSourceName:
        default: "Dynamo DB App CloudWatch Metrics Source Name."

      LambdaARN:
        default: "ARN for lambda."
      RoleARN:
        default: "ARN for Sumo Logic Role."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  DynamoDBDeploymentType:
    Type: String
    AllowedValues:
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-S3Bucket"
    Default: "App-SumoResources-S3Bucket"
    Description: "Only-App: Choose this mode if you already have DynamoDB metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting DynamoDB logs. It installs the collector, source and app.
          App-SumoResources-S3Bucket: Choose this mode if you do not have DynamoDB logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket."

  DynamoDbMetricsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/dynamodb/metrics
  DynamoDbLogsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/dynamodb/logs
  DynamoDbCollectorName:
    Type: String
    Description: Dynamo DB App Collector Name.
    Default: AWS-Observability-Dynamo-DB-Collector
  DynamoDbMetricsSourceName:
    Type: String
    Description: Dynamo DB Gateway App CloudWatch Metrics Source Name.
    Default: AWS-Observability-Dynamo-CloudWatch-Source

  LambdaARN:
    Type: String
    Description: ARN for lambda.
  RoleARN:
    Type: String
    Description: ARN for Sumo Logic Role.
  AWSRegion:
    Type: String
    Description: AWS Region for the resources that need to be tagged.

Conditions:
  setupsumoresources: !Or
    - !Equals [ !Ref DynamoDBDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref DynamoDBDeploymentType, "App-SumoResources-S3Bucket" ]

Resources:

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: setupsumoresources
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref DynamoDbCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchSource:
    DependsOn:
      - SumoHostedCollector
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !Ref AWSRegion
      namespace: AWS/DynamoDB
      SourceName: !Ref DynamoDbMetricsSourceName
      SourceCategory: !Ref DynamoDbMetricsSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !Ref RoleARN

  sumoDynamoDbApp:
    Type: Custom::App
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart DynamoDb App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricsrc: !Sub "_sourceCategory=${DynamoDbMetricsSourceCategoryName}"
        cloudtrail: !Sub "_sourceCategory=${DynamoDbLogsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment