AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - EC2MetricsDeploymentType

      - Label:
          default: "AWS EC2 Metrics App Configuration"
        Parameters:
          - Ec2AppSourceCategoryName

      - Label:
          default: "Local Parameters"
        Parameters:
          - ServiceToken

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      EC2MetricsDeploymentType:
        default: "Do you need to install Resources for AWS EC2 Metrics App?"
      Ec2AppSourceCategoryName:
        default: "EC2 App Metric Data Source Category Name."

      ServiceToken:
        default: "Service token for lambda ARN."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  EC2MetricsDeploymentType:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags"
    Default: "App-SumoResources-AWSTags"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."

  Ec2AppSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/ec2/metrics

  ServiceToken:
    Type: String
    Description: Service token for lambda ARN.

Conditions:
  setupsumoresources: !Or
    - !Equals [ !Ref EC2MetricsDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref EC2MetricsDeploymentType, "App-SumoResources-AWSTags" ]

Resources:

  sumoEC2MetricsApp:
    Type: Custom::App
    Properties:
      ServiceToken: !Ref ServiceToken
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart EC2 Metrics App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        paramId123: !Sub "_sourceCategory=${Ec2AppSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment