AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - SumoOrganizationId
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "Sumo Logic AWS Explorer Configuration (Required)"
        Parameters:
          - AccountAlias

      - Label:
          default: "App Details - Collector Configuration"
        Parameters:
          - CollectorName

      - Label:
          default: "App Details - EC2 Instances Source Category"
        Parameters:
          - MetricsSourceCategoryName

      - Label:
          default: "App Details - MetaData Source Configuration"
        Parameters:
          - CreateMetaDataSource
          - MetaDataSourceName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name"
      SumoAccessID:
        default: "Sumo Logic Access ID"
      SumoAccessKey:
        default: "Sumo Logic Access Key"
      SumoOrganizationId:
        default: "Sumo Logic Organization Id"
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      AccountAlias:
        default: "Alias for AWS Account Identification"

      CollectorName:
        default: "Collector Name"

      MetricsSourceCategoryName:
        default: "Sumo Logic EC2 Instances Metrics Source Category Name"

      CreateMetaDataSource:
        default: "Create Sumo Logic MetaData Source"
      MetaDataSourceName:
        default: "Sumo Logic Metadata Source Name"

      ParentStackName:
        default: "If Any, Name of parent Stack"

Parameters:
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - nite
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
    AllowedPattern: ".+"
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
    AllowedPattern: ".+"
  SumoOrganizationId:
    Type: String
    Description: The Account Overview page displays information about your Sumo Logic organization.
    AllowedPattern: ".+"
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String

  AccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-zA-Z0-9]+"

  CollectorName:
    Type: String
    Description: Change the collector name to be created else default name will be used.
    Default: AWS-EC2-Collector

  MetricsSourceCategoryName:
    Type: String
    Description: "Existing - Provide an existing Source Category from Sumo Logic which collects EC2 metrics."
    AllowedPattern: ".+"

  CreateMetaDataSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic MetaData Source."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  MetaDataSourceName:
    Type: String
    Description: Change the MetaData Source name to be created else default name will be used.
    Default: AWS-EC2-MetaData-Source

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]

  install_metadata_source: !Equals [!Ref CreateMetaDataSource, 'Yes']

Resources:
  SumoLogicHelperRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  SumoLogicHelperFunction:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLogicHelperRole
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !Sub "sumologicawsobservabilityhelper-${AWS::Region}"
        Key: !Sub "sumologic-aws-observability/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLogicHelperRole
          - Arn

  SumoRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::926226587429:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                  - tag:GetResources
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                Resource:
                  "*"

  TagAWSResources:
    Type: Custom::TagAWSResources
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      Region: !Ref "AWS::Region"
      AWSResource: ec2
      Tags:
        account: !Ref AccountAlias
        namespace: "hostmetrics"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  CreateSumoLogicAWSExplorerView:
    Type: Custom::SumoLogicAWSExplorer
    Condition: do_not_use_parent_stack
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      ExplorerName: "AWS Observability"
      MetadataKeys:
        - "account"
        - "region"
        - "namespace"
        - "entity"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  EC2MetricRule:
    Type: Custom::SumoLogicMetricRules
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: !Sub "${AccountAlias}EC2MetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${MetricsSourceCategoryName} InstanceId=*"
      ExtractVariables:
        entity: "$InstanceId._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_metadata_source
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !If [do_not_use_parent_stack, !Ref RemoveSumoResourcesOnDeleteStack, false]
      CollectorName: !Ref CollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoMetaDataSource:
    Condition: install_metadata_source
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsMetadata
      SourceName: !Ref MetaDataSourceName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'

  sumoApp:
    Type: Custom::App
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicHelperFunction
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart EC2 Metrics App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        paramId123: !Sub "_sourceCategory=${MetricsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
