AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - SumoOrganizationId
          - LambdaDeploymentType
          - AWSRegion

      - Label:
          default: "AWS Lambda App Configuration"
        Parameters:
          - LambdaMetricsSourceCategoryName
          - LambdaLogSourceCategoryName
          - LambdaDataEventsSourceCategoryName
          - LambdaCollectorName
          - LambdaMetricsSourceName

      - Label:
          default: "Local Parameters"
        Parameters:
          - LambdaARN
          - RoleARN

      - Label:
          default: "Sumo Logic Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      SumoOrganizationId:
        default: "Sumo Logic Organization Id."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      LambdaDeploymentType:
        default: "Do you need to install Resources for AWS Lambda App?"

      LambdaMetricsSourceCategoryName:
        default: "Lambda App Metric Data Source Category Name."
      LambdaLogSourceCategoryName:
        default: "Lambda App Log Data Source Category Name."
      LambdaDataEventsSourceCategoryName:
        default: "Lambda App Data Events Logs Source Category Name."
      LambdaCollectorName:
        default: "Lambda App Collector Name."
      LambdaMetricsSourceName:
        default: "Lambda App CloudWatch Metrics Source Name."
      LambdaARN:
        default: "ARN for lambda."
      RoleARN:
        default: "ARN for Sumo Logic Role."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."
      QSS3BucketName:
        default: "Quick Start S3 bucket name."
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix."

Parameters:
  SumoOrganizationId:
    Description: The Account Overview page displays information about your Sumo Logic organization.
    Type: String
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  LambdaDeploymentType:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."


  LambdaMetricsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/metrics
  LambdaLogSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/logs
  LambdaDataEventsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/dataevents
  LambdaCollectorName:
    Type: String
    Description: Lambda App Collector Name.
    Default: AWS-Observability-Lambda-Collector
  LambdaMetricsSourceName:
    Type: String
    Description: Lambda Gateway App CloudWatch Metrics Source Name.
    Default: AWS-Observability-Lambda-CloudWatch-Source

  LambdaARN:
    Type: String
    Default: "CreateLambda"
    Description: Service token for lambda ARN. Do Not Edit the value.
  RoleARN:
    Type: String
    Default: "CreateRole"
    Description: Service token for Role ARN. Do Not Edit the value.
  AWSRegion:
    Type: String
    Default: 'Current Region'
    Description: AWS Region for the resources that need to be tagged.
    AllowedValues:
      - 'Current Region'
      - 'All Regions'
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "sumologicawsobservabilityhelper"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "sumologic-aws-observability/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

Conditions:
  CreateRole: !Equals [ !Ref RoleARN, "CreateRole"]
  CreateLambda: !Equals [ !Ref LambdaARN, "CreateLambda"]
  region_value: !Equals [!Ref AWSRegion, 'All Regions']
  setupsumoresources: !Or
    - !Equals [ !Ref LambdaDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-SumoResources-AWSTags-S3Bucket" ]

Resources:
  SumoLambdaRole:
    Type: AWS::IAM::Role
    Condition: CreateLambda
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  SumoLogicAWSObservabilityHelper:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLambdaRole
    Condition: CreateLambda
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !If [CreateLambda, !Sub "${QSS3BucketName}-${AWS::Region}", !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLambdaRole
          - Arn

  SumoRole:
    Type: AWS::IAM::Role
    Condition: CreateRole
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::926226587429:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - tag:GetResources
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                Resource:
                  "*"

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: setupsumoresources
    Properties:
      ServiceToken: !If [CreateLambda, !GetAtt SumoLogicAWSObservabilityHelper.Arn, !Ref LambdaARN]
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref LambdaCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchSource:
    DependsOn:
      - SumoHostedCollector
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !If [CreateLambda, !GetAtt SumoLogicAWSObservabilityHelper.Arn, !Ref LambdaARN]
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !If [region_value, "all", !Ref "AWS::Region"]
      Namespaces:
        - 'AWS/Lambda'
      SourceName: !Ref LambdaMetricsSourceName
      SourceCategory: !Ref LambdaMetricsSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !If [CreateRole, !GetAtt SumoRole.Arn, !Ref RoleARN]

  sumoLambdaApp:
    Type: Custom::App
    Properties:
      ServiceToken: !If [CreateLambda, !GetAtt SumoLogicAWSObservabilityHelper.Arn, !Ref LambdaARN]
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Lambda App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricssrc: !Sub "_sourceCategory=${LambdaMetricsSourceCategoryName}"
        logsrccw: !Sub "_sourceCategory=${LambdaLogSourceCategoryName}"
        logsrcct: !Sub "_sourceCategory=${LambdaDataEventsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment