AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - SumoOrganizationId
          - LambdaDeploymentType
          - AWSRegion

      - Label:
          default: "AWS Lambda App Configuration"
        Parameters:
          - LambdaMetricsSourceCategoryName
          - LambdaCloudWatchLogSourceCategoryName
          - LambdaCloudTrailDataEventsSourceCategoryName
          - LambdaCollectorName
          - LambdaMetricsSourceName
          - LambdaCloudTrailLogsSourceName
          - LambdaCloudWatchLogsSourceName
          - LambdaCloudTrailBucketPathExpression

      - Label:
          default: "AWS Resources Configuration"
        Parameters:
          - LambdaCloudTrailBucketName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

      - Label:
          default: "Sumo Logic Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      SumoOrganizationId:
        default: "Sumo Logic Organization Id."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      LambdaDeploymentType:
        default: "Do you need to install Resources for AWS Lambda App?"

      LambdaMetricsSourceCategoryName:
        default: "Lambda App Metric Data Source Category Name."
      LambdaCloudWatchLogSourceCategoryName:
        default: "Lambda App Cloud Watch Log Data Source Category Name."
      LambdaCloudTrailDataEventsSourceCategoryName:
        default: "Lambda App Cloud Trail Data Events Logs Source Category Name."
      LambdaCollectorName:
        default: "Lambda App Collector Name."
      LambdaMetricsSourceName:
        default: "Lambda App CloudWatch Metrics Source Name."
      LambdaCloudTrailBucketPathExpression:
        default: "Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log"
      LambdaCloudTrailBucketName:
        default: "Lambda App CloudTrail Logs target bucket name."
      LambdaCloudTrailLogsSourceName:
        default: "Lambda App CloudTrail Logs Source Name."
      LambdaCloudWatchLogsSourceName:
        default: "Lambda App CloudWatch Logs Source Name."
      ParentStackName:
        default: "If Any, Name of parent Stack."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."
      QSS3BucketName:
        default: "Quick Start S3 bucket name."
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix."

Parameters:
  SumoOrganizationId:
    Description: The Account Overview page displays information about your Sumo Logic organization.
    Type: String
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  LambdaDeploymentType:
    Type: String
    AllowedValues:
      - "Only-App"
      - "App-CloudTrail"
      - "App-CloudWatchLogs"
      - "App-CloudWatchMetrics"
      - "App-CloudTrail-CloudWatchLogs"
      - "App-CloudTrail-CloudWatchMetrics"
      - "App-CloudWatchLogs-CloudWatchMetrics"
      - "App-CloudTrail-CloudWatchLogs-CloudWatchMetrics"
    Default: "App-CloudTrail-CloudWatchLogs-CloudWatchMetrics"
    Description: "Select the choice as per the below details :-
                  App - Install the app.
                  CloudTrail - Choose to install AWS S3 bucket with CloudTrail source.
                  CloudWatchLogs - Choose to install Cloud Watch Logs Source.
                  CloudWatchMetrics - Choose to install Cloud Watch Metrics Source."


  LambdaMetricsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/metrics
  LambdaCloudWatchLogSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/logs
  LambdaCloudTrailDataEventsSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/lambda/dataevents
  LambdaCollectorName:
    Type: String
    Description: Lambda App Collector Name.
    Default: AWS-Lambda-Collector
  LambdaMetricsSourceName:
    Type: String
    Description: Lambda Gateway App CloudWatch Metrics Source Name.
    Default: AWS-Lambda-CloudWatch-Metrics-Source
  LambdaCloudTrailBucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  LambdaCloudTrailLogsSourceName:
    Type: String
    Description: Lambda App CloudTrail Logs Source Name.
    Default: AWS-Lambda-CloudTrail-Log-Source
  LambdaCloudWatchLogsSourceName:
    Type: String
    Description: Lambda App CloudWatch Logs Source Name.
    Default: AWS-Lambda-CloudWatch-Log-Source
  LambdaCloudTrailBucketName:
    Type: String
    Description: Lambda App CloudTrail Logs target bucket name.
    AllowedPattern: ".+"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.
  AWSRegion:
    Type: String
    Default: 'Current Region'
    Description: AWS Region for the resources that need to be tagged.
    AllowedValues:
      - 'Current Region'
      - 'All Regions'
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "sumologicawsobservabilityhelper"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "sumologic-aws-observability/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]
  region_value: !Equals [!Ref AWSRegion, 'All Regions']
  install_collector: !Not [!Equals [ !Ref LambdaDeploymentType, "Only-App" ]]
  install_cloud_watch_logs_source: !Or
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudWatchLogs" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchLogs" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudWatchLogs-CloudWatchMetrics" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchLogs-CloudWatchMetrics" ]
  install_cloudtrail_source: !Or
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchLogs" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchMetrics" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchLogs-CloudWatchMetrics" ]
  install_cloud_watch_metric_source: !Or
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudWatchMetrics" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchMetrics" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudWatchLogs-CloudWatchMetrics" ]
    - !Equals [ !Ref LambdaDeploymentType, "App-CloudTrail-CloudWatchLogs-CloudWatchMetrics" ]

Resources:
  SumoLambdaRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  SumoLogicAWSObservabilityHelper:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLambdaRole
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !If [do_not_use_parent_stack, !Sub "${QSS3BucketName}-${AWS::Region}", !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLambdaRole
          - Arn

  SumoRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::926226587429:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${SumoDeployment}:${SumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                  - tag:GetResources
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricStatistics
                Resource:
                  "*"

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: install_collector
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref LambdaCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchSource:
    Condition: install_cloud_watch_metric_source
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !If [region_value, "all", !Ref "AWS::Region"]
      Namespaces:
        - 'AWS/Lambda'
      SourceName: !Ref LambdaMetricsSourceName
      SourceCategory: !Ref LambdaMetricsSourceCategoryName
      CollectorId: !If
        - install_collector
        - !GetAtt
          - SumoHostedCollector
          - COLLECTOR_ID
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-CollectorID'
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'

  sumoLambdaApp:
    Type: Custom::App
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Lambda App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        metricssrc: !Sub "_sourceCategory=${LambdaMetricsSourceCategoryName}"
        logsrccw: !Sub "_sourceCategory=${LambdaCloudWatchLogSourceCategoryName}"
        logsrcct: !Sub "_sourceCategory=${LambdaCloudTrailDataEventsSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudTrailExportPolicy:
    Condition: install_cloudtrail_source
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaCloudTrailBucketName
      PolicyDocument:
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${LambdaCloudTrailBucketName}"
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${LambdaCloudTrailBucketName}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSBucketExistenceCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${LambdaCloudTrailBucketName}"
    DependsOn:
      - TargetS3Bucket

  SumoCloudTrail:
    Condition: install_cloudtrail_source
    Type: Custom::AWSTrail
    DependsOn:
      - SumoCloudTrailExportPolicy
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      IsLogging: true
      IsMultiRegionTrail: false
      S3BucketName: !Ref LambdaCloudTrailBucketName
      TrailName: !Sub "SumoCloudTrail-${AWS::StackName}"

  TargetS3Bucket:
    Condition: install_cloudtrail_source
    Type: AWS::S3::Bucket
    DependsOn:
      - SumoSNSpolicy
    Properties:
      BucketName: !Ref LambdaCloudTrailBucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:Put
            Topic: !Ref SumoSNSTopic

  SumoSNSTopic:
    Condition: install_cloudtrail_source
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "SumoSNSTopic-${AWS::StackName}"

  SumoSNSSubscription:
    Condition: install_cloudtrail_source
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn:
        Ref: SumoSNSTopic
      Endpoint: !GetAtt SumoCloudTrailSource.SUMO_ENDPOINT
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 40
          minDelayTarget: 10
          maxDelayTarget: 300
          numMinDelayRetries: 3
          numMaxDelayRetries: 5
          numNoDelayRetries: 0
          backoffFunction: exponential

  SumoSNSpolicy:
    Condition: install_cloudtrail_source
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SumoTopicPolicy
        Statement:
          - Action:
              - sns:Publish
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref "AWS::AccountId"
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${LambdaCloudTrailBucketName}"
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              - !Ref SumoSNSTopic
      Topics:
        - Ref: SumoSNSTopic

  SumoCloudTrailSource:
    Condition: install_cloudtrail_source
    Type: Custom::AWSSource
    Properties:
      SourceType: AwsCloudTrailBucket
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      SourceName: !Ref LambdaCloudTrailLogsSourceName
      TargetBucketName: !Ref LambdaCloudTrailBucketName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref LambdaCloudTrailDataEventsSourceCategoryName
      CollectorId: !If
        - install_collector
        - !GetAtt
          - SumoHostedCollector
          - COLLECTOR_ID
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-CollectorID'
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      PathExpression: !Ref LambdaCloudTrailBucketPathExpression
      RoleArn: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoRole
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoSourceRoleARN'
    DependsOn:
      - SumoLogicAWSObservabilityHelper

  CloudWatchEventFunction:
    Condition: install_cloud_watch_logs_source
    Properties:
      CodeUri:
        Bucket: !If [do_not_use_parent_stack, !Sub "${QSS3BucketName}-${AWS::Region}", !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}SumoLogicAWSObservabilityHelper/SumoLogicCloudWatchEvents.zip"
      Environment:
        Variables:
          SUMO_ENDPOINT: !GetAtt SumoHTTPSource.SUMO_ENDPOINT
      Events:
        CloudWatchEventTrigger:
          Properties:
            Pattern:
              source:
                - aws.guardduty
          Type: CloudWatchEvent
      Handler: cloudwatchevents.handler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  SumoHTTPSource:
    Condition: install_cloud_watch_logs_source
    Type: Custom::HTTPSource
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicLambdaHelperARN'
      Region: !Ref "AWS::Region"
      SourceName: !Ref LambdaCloudWatchLogsSourceName
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceCategory: !Ref LambdaCloudWatchLogSourceCategoryName
      CollectorId: !If
        - install_collector
        - !GetAtt
          - SumoHostedCollector
          - COLLECTOR_ID
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-CollectorID'
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      DateFormat: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
      DateLocatorRegex: '.*"updatedAt":"(.*)".*'