AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "AWS Resources Tag Configuration"
        Parameters:
          - AccountAlias

      - Label:
          default: "Select the AWS Resources you want to tag:"
        Parameters:
          - AddMetricRuleForALB
          - AddMetricRuleForAPIGateway
          - AddMetricRuleForRDS
          - AddMetricRuleForEC2Metrics
          - AddMetricRuleForLambda
          - AddMetricRuleForDynamoDB

      - Label:
          default: "Source Categories :"
        Parameters:
          - EC2SourceCategory
          - RDSSourceCategory
          - APISourceCategory
          - ALBSourceCategory
          - DynamoDBSourceCategory
          - LambdaSourceCategory

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - ParentStackName

      - Label:
          default: "Sumo Logic Quick Start configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."

      AccountAlias:
        default: "Value for Account Tag."

      AddMetricRuleForALB:
        default: "Do you need to add Metric Rule for AWS ALB?"
      AddMetricRuleForAPIGateway:
        default: "Do you need to add Metric Rule for AWS API Gateway?"
      AddMetricRuleForRDS:
        default: "Do you need to add Metric Rule for AWS RDS?"
      AddMetricRuleForEC2Metrics:
        default: "Do you need to add Metric Rule for AWS EC2 Metrics?"
      AddMetricRuleForLambda:
        default: "Do you need to add Metric Rule for AWS Lambda?"
      AddMetricRuleForDynamoDB:
        default: "Do you need to add Metric Rule for AWS Dynamo DB?"

      EC2SourceCategory:
        default: "Source Category for EC2 Metrics"
      RDSSourceCategory:
        default: "Source Category for RDS Metrics"
      APISourceCategory:
        default: "Source Category for API Gateway Metrics"
      ALBSourceCategory:
        default: "Source Category for ALB Metrics"
      DynamoDBSourceCategory:
        default: "Source Category for Dynamo DB Metrics"
      LambdaSourceCategory:
        default: "Source Category for Lambda Metrics"

      ParentStackName:
        default: "If Any, Name of parent Stack."
      QSS3BucketName:
        default: "Quick Start S3 bucket name."
      QSS3KeyPrefix:
        default: "Quick Start S3 key prefix."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - nite
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String

  AccountAlias:
    Type: String
    Description: Provide the Value for Account Tag.

  AddMetricRuleForALB:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."
  AddMetricRuleForAPIGateway:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."
  AddMetricRuleForRDS:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."
  AddMetricRuleForEC2Metrics:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."
  AddMetricRuleForLambda:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."
  AddMetricRuleForDynamoDB:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Choose if you need to add Metric Rule."

  EC2SourceCategory:
    Type: String
    Default: ""
    Description: "Source category for EC2 Metrics"
  RDSSourceCategory:
    Type: String
    Default: ""
    Description: "Source category for RDS Metrics"
  APISourceCategory:
    Type: String
    Default: ""
    Description: "Source category for API Gateway Metrics"
  ALBSourceCategory:
    Type: String
    Default: ""
    Description: "Source category for ALB Metrics"
  DynamoDBSourceCategory:
    Type: String
    Default: ""
    Description: "Source category for Dynamo DB Metrics"
  LambdaSourceCategory:
    Type: String
    Default: ""
    Description: "Source category for Lambda Metrics"

  ParentStackName:
    Type: String
    Default: "ParentStackName"
    Description: Parent Stack Name. Do Not Edit the value.
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "sumologicawsobservabilityhelper"
    Description: "S3 bucket name for the Quick Start assets. This string can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "sumologic-aws-observability/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

Conditions:
  add_alb_rule: !Equals [!Ref AddMetricRuleForALB, 'Yes']
  add_api_gateway_rule: !Equals [!Ref AddMetricRuleForAPIGateway, 'Yes']
  add_rds_rule: !Equals [!Ref AddMetricRuleForRDS, 'Yes']
  add_ec2_metrics_rule: !Equals [!Ref AddMetricRuleForEC2Metrics, 'Yes']
  add_lambda_rule: !Equals [!Ref AddMetricRuleForLambda, 'Yes']
  add_dynamo_rule: !Equals [!Ref AddMetricRuleForDynamoDB, 'Yes']
  do_not_use_parent_stack: !Equals [ !Ref ParentStackName, "ParentStackName"]

Resources:

  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  SumoLambdaRole:
    Type: AWS::IAM::Role
    Condition: do_not_use_parent_stack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SumoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  SumoLogicAWSObservabilityHelper:
    Type: 'AWS::Serverless::Function'
    DependsOn: SumoLambdaRole
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !If [do_not_use_parent_stack, !Sub "${QSS3BucketName}-${AWS::Region}", !Ref QSS3BucketName]
        Key: !Sub "${QSS3KeyPrefix}SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelper.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - SumoLambdaRole
          - Arn

  EC2MetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_ec2_metrics_rule
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "EC2MetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${EC2SourceCategory} InstanceId=*"
      ExtractVariables:
        entity: "$InstanceId._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  EC2StackWaitHandle:
    Condition: add_ec2_metrics_rule
    DependsOn: EC2MetricRule
    Type: "AWS::CloudFormation::WaitConditionHandle"

  EC2StackWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [add_ec2_metrics_rule, !Ref EC2StackWaitHandle, !Ref WaitHandle]
      Timeout: "5"
      Count: 0

  RDSMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_rds_rule
    DependsOn: EC2StackWaitCondition
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "RDSMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${RDSSourceCategory} Namespace=AWS/RDS cluster=*"
      ExtractVariables:
        entity: "$cluster._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  RDSStackWaitHandle:
    Condition: add_rds_rule
    DependsOn: RDSMetricRule
    Type: "AWS::CloudFormation::WaitConditionHandle"

  RDSStackWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [add_rds_rule, !Ref RDSStackWaitHandle, !Ref WaitHandle]
      Timeout: "5"
      Count: 0

  ALBMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_alb_rule
    DependsOn: RDSStackWaitCondition
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "ALBMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${ALBSourceCategory} Namespace=AWS/ApplicationELB LoadBalancer=*"
      ExtractVariables:
        entity: "$LoadBalancer._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  LambdaMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_lambda_rule
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "LambdaMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${LambdaSourceCategory} Namespace=AWS/Lambda FunctionName=*"
      ExtractVariables:
        entity: "$FunctionName._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  LambdaStackWaitHandle:
    Condition: add_lambda_rule
    DependsOn: LambdaMetricRule
    Type: "AWS::CloudFormation::WaitConditionHandle"

  LambdaStackWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [add_lambda_rule, !Ref LambdaStackWaitHandle, !Ref WaitHandle]
      Timeout: "5"
      Count: 0

  APIGatewayMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_api_gateway_rule
    DependsOn: LambdaStackWaitCondition
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "ApiGatewayMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${APISourceCategory} Namespace=AWS/ApiGateway ApiName=*"
      ExtractVariables:
        entity: "$ApiName._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  APIStackWaitHandle:
    Condition: add_api_gateway_rule
    DependsOn: APIGatewayMetricRule
    Type: "AWS::CloudFormation::WaitConditionHandle"

  APIStackWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [add_api_gateway_rule, !Ref APIStackWaitHandle, !Ref WaitHandle]
      Timeout: "5"
      Count: 0

  DynamoMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_dynamo_rule
    DependsOn: APIStackWaitCondition
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "DynamoTableMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${DynamoDBSourceCategory} Namespace=AWS/DynamoDB TableName=*"
      ExtractVariables:
        entity: "$TableName._1"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  DynamoStackWaitHandle:
    Condition: add_dynamo_rule
    DependsOn: DynamoMetricRule
    Type: "AWS::CloudFormation::WaitConditionHandle"

  DynamoStackWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !If [add_dynamo_rule, !Ref DynamoStackWaitHandle, !Ref WaitHandle]
      Timeout: "5"
      Count: 0

  DynamoAccountMetricRule:
    Type: Custom::SumoLogicMetricRules
    Condition: add_dynamo_rule
    DependsOn: DynamoStackWaitCondition
    Properties:
      ServiceToken: !If
        - do_not_use_parent_stack
        - !GetAtt
          - SumoLogicAWSObservabilityHelper
          - Arn
        - !ImportValue
          'Fn::Sub': '${ParentStackName}-SumoLogicHelperFunctionARN'
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      MetricRuleName: "DynamoAccountMetricsEntityRule"
      MatchExpression: !Sub "_sourceCategory=${DynamoDBSourceCategory} Namespace=AWS/DynamoDB"
      ExtractVariables:
        account: !Sub "${AccountAlias}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment