AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack
          - RDSDeploymentType

      - Label:
          default: "AWS RDS App Configuration"
        Parameters:
          - RdsAppSourceCategoryName
          - RdsCollectorName
          - RdsSourceName

      - Label:
          default: "Local Parameters"
        Parameters:
          - LambdaARN
          - RoleARN
          - AWSRegion

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      RDSDeploymentType:
        default: "Do you need to install Resources for AWS RDS App?"

      RdsAppSourceCategoryName:
        default: "RDS App Metric Data Source Category Name."
      RdsCollectorName:
        default: "RDS App Collector Name."
      RdsSourceName:
        default: "RDS App CloudWatch Metrics Source Name."
      LambdaARN:
        default: "ARN for lambda."
      RoleARN:
        default: "ARN for Sumo Logic Role."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String
  RDSDeploymentType:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags"
    Default: "App-SumoResources-AWSTags"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."

  RdsAppSourceCategoryName:
    Type: String
    Description: Category metadata to use later for querying, e.g. prod/web/apache/access . This data is queried using the '_sourceCategory' key name.
    Default: AWS/rds/metrics
  RdsCollectorName:
    Type: String
    Description: RDS App Collector Name.
    Default: AWS-Observability-RDS-Collector
  RdsSourceName:
    Type: String
    Description: RDS App CloudWatch Metrics Source Name.
    Default: AWS-Observability-RDS-CloudWatch-Source

  LambdaARN:
    Type: String
    Description: ARN for lambda.
  RoleARN:
    Type: String
    Description: ARN for Sumo Logic Role.
  AWSRegion:
    Type: String
    Description: AWS Region for the resources that need to be tagged.

Conditions:
  setupsumoresources: !Or
    - !Equals [ !Ref RDSDeploymentType, "App-SumoResources" ]
    - !Equals [ !Ref RDSDeploymentType, "App-SumoResources-AWSTags" ]

Resources:

  SumoHostedCollector:
    Type: Custom::Collector
    Condition: setupsumoresources
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref RdsCollectorName
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  SumoCloudwatchSource:
    DependsOn:
      - SumoHostedCollector
    Type: Custom::AWSSource
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      SourceType: AwsCloudWatch
      AWSRegion: !Ref AWSRegion
      namespace: AWS/RDS
      SourceName: !Ref RdsSourceName
      SourceCategory: !Ref RdsAppSourceCategoryName
      CollectorId: !GetAtt SumoHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
      RoleArn: !Ref RoleARN

  sumoRdsApp:
    Type: Custom::App
    Properties:
      ServiceToken: !Ref LambdaARN
      Region: !Ref "AWS::Region"
      AppName: "Amazon QuickStart Rds App"
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AppSources:
        paramId123: !Sub "_sourceCategory=${RdsAppSourceCategoryName}"
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment