AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Deployment Configuration (Required)"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
          - RemoveSumoResourcesOnDeleteStack

      - Label:
          default: "AWS Resources Tag Configuration"
        Parameters:
          - AWSRegion
          - AccountAlias
          - ServiceToken

      - Label:
          default: "Select the AWS Resources you want to tag:"
          Parameters:
            - AddTagsForALBResources
            - AddTagsForAPIGatewayResources
            - AddTagsForRDSResources
            - AddTagsForEC2MetricsResources
            - AddTagsForLambdaResources

    ParameterLabels:
      SumoDeployment:
        default: "Sumo Logic Deployment Name."
      SumoAccessID:
        default: "Sumo Logic Access ID."
      SumoAccessKey:
        default: "Sumo Logic Access Key."
      RemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted."
      AWSRegion:
        default: "AWS Region for the resources that need to be tagged."
      AccountAlias:
        default: "Value for Account Tag."
      ServiceToken:
        default: "Service token for lambda ARN."
      AddTagsForALBResources:
        default: "Do you need to add Tags for AWS ALB Resources?"
      AddTagsForAPIGatewayResources:
        default: "Do you need to add Tags for AWS API Gateway Resources?"
      AddTagsForRDSResources:
        default: "Do you need to add Tags for AWS RDS Resources?"
      AddTagsForEC2MetricsResources:
        default: "Do you need to add Tags for AWS EC2 Metrics Resources?"
      AddTagsForLambdaResources:
        default: "Do you need to add Tags for AWS Lambda Resources?"

Parameters:
  SumoAccessID:
    Type: String
    Description: The Sumo Logic Access ID.
  SumoAccessKey:
    Type: String
    Description: The Sumo Logic Access Key.
  SumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
    Description: "Enter au, ca, de, eu, jp, us2, or us1."
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: To delete collector, sources and app when stack is deleted, set this parameter to true. Default is true.
    Type: String

  AccountAlias:
    Type: String
    Description: Provide the Value for Account Tag.
  AWSRegion:
    Type: String
    Description: AWS Region for the resources that need to be tagged.
  ServiceToken:
    Type: String
    Description: Service token for lambda ARN.

  AddTagsForALBResources:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
            Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
            App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
            App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."
  AddTagsForAPIGatewayResources:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."
  AddTagsForRDSResources:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags"
    Default: "App-SumoResources-AWSTags"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."
  AddTagsForEC2MetricsResources:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags"
    Default: "App-SumoResources-AWSTags"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
          Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
          App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
          App-SumoResources-AWSTags: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."
  AddTagsForLambdaResources:
    Type: String
    AllowedValues:
      - "Only-AWSTags"
      - "Only-App"
      - "App-SumoResources"
      - "App-SumoResources-AWSTags-S3Bucket"
    Default: "App-SumoResources-AWSTags-S3Bucket"
    Description: "Only-AWSTags: Choose this mode if you need to only tag your AWS Resources.
                Only-App: Choose this mode if you already have metrics and logs in Sumo. It installs only the app.
                App-SumoResources: Choose this mode if you already have a S3 bucket which is getting logs. It installs the collector, source and app.
                App-SumoResources-AWSTags-S3Bucket: Choose this mode if you do not have logs and Metrics configured in your AWS Account. It deploys the collector, source, app, s3-bucket and Tags."

Conditions:
  add_alb_tags: !Or
    - !Equals [ !Ref AddTagsForALBResources, "Only-AWSTags" ]
    - !Equals [ !Ref AddTagsForALBResources, "App-SumoResources-AWSTags-S3Bucket" ]
  add_api_gateway_tags: !Or
    - !Equals [ !Ref AddTagsForALBResources, "Only-AWSTags" ]
    - !Equals [ !Ref AddTagsForALBResources, "App-SumoResources-AWSTags-S3Bucket" ]
  add_rds_tags: !Or
    - !Equals [ !Ref AddTagsForALBResources, "Only-AWSTags" ]
    - !Equals [ !Ref AddTagsForALBResources, "App-SumoResources-AWSTags" ]
  add_ec2_metrics_tags: !Or
    - !Equals [ !Ref AddTagsForALBResources, "Only-AWSTags" ]
    - !Equals [ !Ref AddTagsForALBResources, "App-SumoResources-AWSTags" ]
  add_lambda_tags: !Or
    - !Equals [ !Ref AddTagsForALBResources, "Only-AWSTags" ]
    - !Equals [ !Ref AddTagsForALBResources, "App-SumoResources-AWSTags-S3Bucket" ]

Resources:

  TagEc2Resources:
    Type: Custom::TagAWSResources
    Condition: add_ec2_metrics_tags
    Properties:
      ServiceToken: !Ref ServiceToken
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSRegion: !Ref AWSRegion
      AWSResource: ec2
      Account: !Ref AccountAlias
      Namespace: hostmetrics
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  TagAlbResources:
    Type: Custom::TagAWSResources
    Condition: add_alb_tags
    Properties:
      ServiceToken: !Ref ServiceToken
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSRegion: !Ref AWSRegion
      AWSResource: elbv2
      Account: !Ref AccountAlias
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  TagApiGatewayResources:
    Type: Custom::TagAWSResources
    Condition: add_api_gateway_tags
    Properties:
      ServiceToken: !Ref ServiceToken
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSRegion: !Ref AWSRegion
      AWSResource: apigateway
      Account: !Ref AccountAlias
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  TagLambdaResources:
    Type: Custom::TagAWSResources
    Condition: add_lambda_tags
    Properties:
      ServiceToken: !Ref ServiceToken
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSRegion: !Ref AWSRegion
      AWSResource: lambda
      Account: !Ref AccountAlias
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment

  TagRdsResources:
    Type: Custom::TagAWSResources
    Condition: add_rds_tags
    Properties:
      ServiceToken: !Ref ServiceToken
      RemoveOnDeleteStack: !Ref RemoveSumoResourcesOnDeleteStack
      AWSRegion: !Ref AWSRegion
      AWSResource: rds
      Account: !Ref AccountAlias
      SumoAccessID: !Ref SumoAccessID
      SumoAccessKey: !Ref SumoAccessKey
      SumoDeployment: !Ref SumoDeployment
