AWSTemplateFormatVersion: '2010-09-09'
Description: '"Lambda Function for automatic subscription of any Sumo Logic lambda
  function with loggroups matching an input pattern."

  '
Globals:
  Function:
    MemorySize: 128
    Timeout: 300
Outputs:
  SumoLogGroupLambdaConnector:
    Description: SumoLogGroupLambdaConnector Function ARN
    Value:
      Fn::GetAtt:
      - SumoLogGroupLambdaConnector
      - Arn
Parameters:
  LambdaARN:
    Default: arn:aws:lambda:us-east-1:123456789000:function:TestLambda
    Description: Enter ARN for target lambda function
    Type: String
  LogGroupPattern:
    Default: Test
    Description: Enter regex for matching logGroups
    Type: String
  UseExistingLogs:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Description: Select true for subscribing existing logs
    Type: String
Resources:
  SumoCWLambdaInvokePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaARN
      Principal:
        Fn::Sub: logs.${AWS::Region}.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*
    Type: AWS::Lambda::Permission
  SumoLogGroupLambdaConnector:
    Properties:
      CodeUri: s3://appdevstore/6bef113d950a9923b446dd438116f2a1
      Environment:
        Variables:
          LAMBDA_ARN:
            Ref: LambdaARN
          LOG_GROUP_PATTERN:
            Ref: LogGroupPattern
          USE_EXISTING_LOG_GROUPS:
            Ref: UseExistingLogs
      Events:
        LambdaTrigger:
          Properties:
            Pattern:
              detail:
                eventName:
                - CreateLogGroup
                eventSource:
                - logs.amazonaws.com
              source:
              - aws.logs
          Type: CloudWatchEvent
      Handler: loggroup-lambda-connector.handler
      Policies:
      - Statement:
        - Action:
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
          - logs:PutSubscriptionFilter
          Effect: Allow
          Resource:
          - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
          Sid: ReadWriteFilterPolicy
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
