AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This solution consists of a lambda function which which gets triggered
  when CF stack is deployed. This is used for creating sumologic resources like collector,
  source and app folders.

  '
Globals:
  Function:
    Timeout: 300
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda function which which gets triggered
      when CF stack is deployed. This is used for creating sumologic resources like
      collector, source and app folders.
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - lambda
    - sumologic
    - serverless
    Name: sumologic-app-utils
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda/tree/master/sumologic-app-utils
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: s3://appdevstore/sumo_app_utils/v2.0.0/d261225f897cba410fd32b71c9991539
Parameters:
  RoleArn:
    Type: String
    Description: Attach any existing Role ARN to Lambda Function. If no Existing Role
      ARN is provided, a role will be created and attached to the lambda function.
    Default: ''
Conditions:
  role_arn:
    Fn::Not:
    - Fn::Equals:
      - Ref: RoleArn
      - ''
  No_role_arn:
    Fn::Equals:
    - Ref: RoleArn
    - ''
Resources:
  SumoAppUtilsFunctionWithRole:
    Type: AWS::Serverless::Function
    Condition: role_arn
    Properties:
      Handler: main.handler
      FunctionName:
        Fn::Join:
        - ''
        - - sumo-logic-app-utils-
          - Fn::Select:
            - 0
            - Fn::Split:
              - '-'
              - Fn::Select:
                - 2
                - Fn::Split:
                  - /
                  - Ref: AWS::StackId
      Runtime: python3.7
      CodeUri: s3://appdevstore/sumo_app_utils/v2.0.0/sumo_app_utils.zip
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::If:
        - role_arn
        - Ref: RoleArn
        - Ref: AWS::NoValue
  SumoAppUtilsFunction:
    Type: AWS::Serverless::Function
    Condition: No_role_arn
    Properties:
      Handler: main.handler
      FunctionName:
        Fn::Join:
        - ''
        - - sumo-logic-app-utils-
          - Fn::Select:
            - 0
            - Fn::Split:
              - '-'
              - Fn::Select:
                - 2
                - Fn::Split:
                  - /
                  - Ref: AWS::StackId
      Runtime: python3.7
      CodeUri: s3://appdevstore/sumo_app_utils/v2.0.0/sumo_app_utils.zip
      MemorySize: 128
      Timeout: 300
      Policies:
      - Statement:
        - Action:
          - cloudtrail:CreateTrail
          - cloudtrail:DeleteTrail
          - cloudtrail:UpdateTrail
          - cloudtrail:StartLogging
          Effect: Allow
          Resource: arn:aws:cloudtrail:*:*:*
          Sid: CreateCloudTrailPolicy
Outputs:
  SumoAppUtilsFunction:
    Description: SumoAppUtils Function ARN
    Value:
      Fn::If:
      - role_arn
      - Fn::GetAtt:
        - SumoAppUtilsFunctionWithRole
        - Arn
      - Fn::GetAtt:
        - SumoAppUtilsFunction
        - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SumoAppUtilsFunction
