AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This solution consists of two lambda functions which are used to fetch
  findings from AWS Security Hub and ingest to Sumo Logic.

  '
Globals:
  Function:
    Timeout: 300
Parameters:
  S3SourceBucketName:
    Type: String
Resources:
  SecurityHubCollectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: securityhub_collector.lambda_handler
      Runtime: python3.7
      CodeUri: s3://appdevstore/4f53828416975cb22a96ae1aaf6dcd6c
      MemorySize: 128
      Timeout: 300
      Policies:
      - Statement:
        - Sid: SecurityHubS3PutObjectPolicy
          Effect: Allow
          Action:
          - s3:PutObject
          Resource:
          - Fn::Sub: arn:aws:s3:::${S3SourceBucketName}
          - Fn::Sub: arn:aws:s3:::${S3SourceBucketName}/*
      Environment:
        Variables:
          S3_LOG_BUCKET:
            Ref: S3SourceBucketName
      Events:
        CloudWatchEventTrigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.securityhub
Outputs:
  SecurityHubCollectorFunction:
    Description: SecurityHubCollector Function ARN
    Value:
      Fn::GetAtt:
      - SecurityHubCollectorFunction
      - Arn
